#!/usr/bin/env python
"""Build demo-site/data.js from the committed results/ JSONs.

    python demo-site/build.py        # from the repo root

Everything the explorer renders is a committed measurement; nothing is
hand-typed. Re-run after regenerating results.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"

MODELS = ["transformer", "s4d", "mamba", "mamba2", "mamba3"]
LABELS = {
    "transformer": "Transformer",
    "s4d": "S4D (LTI)",
    "mamba": "Mamba-1",
    "mamba2": "Mamba-2 (SSD)",
    "mamba3": "Mamba-3 (complex)",
}


def load(name: str) -> dict:
    return json.loads((RESULTS / name).read_text(encoding="utf-8"))


def final(run: dict, key: str):
    for entry in reversed(run.get("history", [])):
        if entry.get(key) is not None:
            return entry[key]
    return None


def task_results(prefix: str, keys: list[str]) -> dict:
    out = {}
    for model in MODELS:
        path = RESULTS / f"{prefix}_{model}.json"
        if path.exists():
            run = load(path.name)
            out[model] = {k: final(run, k) for k in keys}
    return out


def exact_copy_in_dist() -> dict:
    out = {}
    for model in MODELS:
        path = RESULTS / f"exact_copy_{model}.json"
        if path.exists():
            run = load(path.name)
            by_len = run.get("final_by_length") or {}
            in_dist = by_len.get("32", {})
            out[model] = {
                "sequence_success": in_dist.get("sequence_success"),
                "token_accuracy": in_dist.get("token_accuracy"),
            }
    return out


eff = load("efficiency_gpu.json")
data = {
    "environment": eff.get("environment", {}),
    "models": [{"id": m, "label": LABELS[m]} for m in MODELS],
    "parity": task_results("parity", ["token_accuracy", "sequence_success"]),
    "selective_copy": task_results("selective_copy", ["sequence_success", "token_accuracy"]),
    "exact_copy_in_dist": exact_copy_in_dist(),
    "imdb": task_results("imdb", ["accuracy", "auc"]),
    "efficiency": [
        {
            "model": e.get("model"),
            "seq_len": e.get("seq_len"),
            "train_step_ms": e.get("train_step_ms"),
            "peak_train_mb": e.get("peak_train_mb"),
            "train_tokens_per_s": e.get("train_tokens_per_s"),
            "decode_per_token_ms": e.get("decode_per_token_ms"),
            "decode_mode": e.get("decode_mode"),
            "oom": bool(e.get("oom") or e.get("oom_train") or e.get("oom_infer")),
        }
        for e in eff.get("entries", [])
    ],
}

out_path = Path(__file__).resolve().parent / "data.js"
out_path.write_text(
    "// Generated by demo-site/build.py from committed results/ - do not hand-edit.\n"
    "window.DATA = " + json.dumps(data, indent=1) + ";\n",
    encoding="utf-8",
)
print(f"wrote {out_path}")
