// Generated by demo-site/build.py from committed results/ - do not hand-edit.
window.DATA = {
 "environment": {
  "date": "2026-09-16",
  "device": "cuda",
  "gpu": "NVIDIA GeForce RTX 4050 Laptop GPU",
  "torch": "2.14.0+cu130"
 },
 "models": [
  {
   "id": "transformer",
   "label": "Transformer"
  },
  {
   "id": "s4d",
   "label": "S4D (LTI)"
  },
  {
   "id": "mamba",
   "label": "Mamba-1"
  },
  {
   "id": "mamba2",
   "label": "Mamba-2 (SSD)"
  },
  {
   "id": "mamba3",
   "label": "Mamba-3 (complex)"
  }
 ],
 "parity": {
  "transformer": {
   "token_accuracy": 0.532953125,
   "sequence_success": 0.0
  },
  "s4d": {
   "token_accuracy": 0.506484375,
   "sequence_success": 0.0
  },
  "mamba": {
   "token_accuracy": 0.5591484375,
   "sequence_success": 0.0
  },
  "mamba2": {
   "token_accuracy": 0.563,
   "sequence_success": 0.0
  },
  "mamba3": {
   "token_accuracy": 0.9834296875,
   "sequence_success": 0.42
  }
 },
 "selective_copy": {
  "transformer": {
   "sequence_success": 0.0,
   "token_accuracy": 0.2047486482145725
  },
  "s4d": {
   "sequence_success": 0.0,
   "token_accuracy": 0.06408265967128861
  },
  "mamba": {
   "sequence_success": 0.149,
   "token_accuracy": 0.649204989560469
  },
  "mamba2": {
   "sequence_success": 0.1834,
   "token_accuracy": 0.6696557631564859
  },
  "mamba3": {
   "sequence_success": 0.1294,
   "token_accuracy": 0.21537555543658654
  }
 },
 "exact_copy_in_dist": {
  "transformer": {
   "sequence_success": 1.0,
   "token_accuracy": 1.0
  },
  "s4d": {
   "sequence_success": 1.0,
   "token_accuracy": 1.0
  },
  "mamba": {
   "sequence_success": 0.0,
   "token_accuracy": 0.10594223484848485
  },
  "mamba2": {
   "sequence_success": 0.0,
   "token_accuracy": 0.1503314393939394
  }
 },
 "imdb": {
  "transformer": {
   "accuracy": 0.81348,
   "auc": 0.8939710848
  },
  "s4d": {
   "accuracy": 0.82676,
   "auc": 0.9065102208
  },
  "mamba2": {
   "accuracy": 0.83612,
   "auc": 0.9169082399999999
  }
 },
 "efficiency": [
  {
   "model": "transformer",
   "seq_len": 1024,
   "train_step_ms": 30.09,
   "peak_train_mb": 419.0,
   "train_tokens_per_s": 272237,
   "decode_per_token_ms": 0.0015,
   "decode_mode": "full-prefix recompute (no KV cache)",
   "oom": false
  },
  {
   "model": "transformer",
   "seq_len": 2048,
   "train_step_ms": 81.91,
   "peak_train_mb": 724.6,
   "train_tokens_per_s": 200035,
   "decode_per_token_ms": 0.0016,
   "decode_mode": "full-prefix recompute (no KV cache)",
   "oom": false
  },
  {
   "model": "transformer",
   "seq_len": 4096,
   "train_step_ms": 250.31,
   "peak_train_mb": 1333.9,
   "train_tokens_per_s": 130911,
   "decode_per_token_ms": 0.0022,
   "decode_mode": "full-prefix recompute (no KV cache)",
   "oom": false
  },
  {
   "model": "transformer",
   "seq_len": 8192,
   "train_step_ms": 846.56,
   "peak_train_mb": 2552.4,
   "train_tokens_per_s": 77415,
   "decode_per_token_ms": 0.0034,
   "decode_mode": "full-prefix recompute (no KV cache)",
   "oom": false
  },
  {
   "model": "transformer",
   "seq_len": 16384,
   "train_step_ms": 4482.01,
   "peak_train_mb": 4989.4,
   "train_tokens_per_s": 29244,
   "decode_per_token_ms": 0.0059,
   "decode_mode": "full-prefix recompute (no KV cache)",
   "oom": false
  },
  {
   "model": "transformer",
   "seq_len": 32768,
   "train_step_ms": 186025.38,
   "peak_train_mb": 9879.4,
   "train_tokens_per_s": 1409,
   "decode_per_token_ms": 0.0107,
   "decode_mode": "full-prefix recompute (no KV cache)",
   "oom": false
  },
  {
   "model": "s4d",
   "seq_len": 1024,
   "train_step_ms": 19.51,
   "peak_train_mb": 293.7,
   "train_tokens_per_s": 419908,
   "decode_per_token_ms": 1.7284,
   "decode_mode": "stepwise (O(1) state)",
   "oom": false
  },
  {
   "model": "s4d",
   "seq_len": 2048,
   "train_step_ms": 43.44,
   "peak_train_mb": 567.9,
   "train_tokens_per_s": 377175,
   "decode_per_token_ms": 2.2129,
   "decode_mode": "stepwise (O(1) state)",
   "oom": false
  },
  {
   "model": "s4d",
   "seq_len": 4096,
   "train_step_ms": 84.89,
   "peak_train_mb": 1116.5,
   "train_tokens_per_s": 386005,
   "decode_per_token_ms": 1.8288,
   "decode_mode": "stepwise (O(1) state)",
   "oom": false
  },
  {
   "model": "s4d",
   "seq_len": 8192,
   "train_step_ms": 169.6,
   "peak_train_mb": 2213.5,
   "train_tokens_per_s": 386412,
   "decode_per_token_ms": 1.8354,
   "decode_mode": "stepwise (O(1) state)",
   "oom": false
  },
  {
   "model": "s4d",
   "seq_len": 16384,
   "train_step_ms": 741.04,
   "peak_train_mb": 4919.5,
   "train_tokens_per_s": 176876,
   "decode_per_token_ms": 1.615,
   "decode_mode": "stepwise (O(1) state)",
   "oom": false
  },
  {
   "model": "s4d",
   "seq_len": 32768,
   "train_step_ms": 13456.29,
   "peak_train_mb": 9819.7,
   "train_tokens_per_s": 19481,
   "decode_per_token_ms": 1.6026,
   "decode_mode": "stepwise (O(1) state)",
   "oom": false
  },
  {
   "model": "mamba2",
   "seq_len": 1024,
   "train_step_ms": 78.54,
   "peak_train_mb": 754.2,
   "train_tokens_per_s": 104302,
   "decode_per_token_ms": 0.0069,
   "decode_mode": "sequential scan over full sequence (per-token = time/T)",
   "oom": false
  },
  {
   "model": "mamba2",
   "seq_len": 2048,
   "train_step_ms": 222.66,
   "peak_train_mb": 1484.2,
   "train_tokens_per_s": 73583,
   "decode_per_token_ms": 0.0059,
   "decode_mode": "sequential scan over full sequence (per-token = time/T)",
   "oom": false
  },
  {
   "model": "mamba2",
   "seq_len": 4096,
   "train_step_ms": 842.33,
   "peak_train_mb": 2939.0,
   "train_tokens_per_s": 38902,
   "decode_per_token_ms": 0.0055,
   "decode_mode": "sequential scan over full sequence (per-token = time/T)",
   "oom": false
  },
  {
   "model": "mamba2",
   "seq_len": 8192,
   "train_step_ms": 8953.79,
   "peak_train_mb": 5852.1,
   "train_tokens_per_s": 7319,
   "decode_per_token_ms": 0.0072,
   "decode_mode": "sequential scan over full sequence (per-token = time/T)",
   "oom": false
  },
  {
   "model": "mamba2",
   "seq_len": 16384,
   "train_step_ms": 130426.11,
   "peak_train_mb": 11678.2,
   "train_tokens_per_s": 1005,
   "decode_per_token_ms": 0.0069,
   "decode_mode": "sequential scan over full sequence (per-token = time/T)",
   "oom": false
  },
  {
   "model": "mamba2",
   "seq_len": 32768,
   "train_step_ms": null,
   "peak_train_mb": null,
   "train_tokens_per_s": null,
   "decode_per_token_ms": null,
   "decode_mode": null,
   "oom": true
  },
  {
   "model": "mamba",
   "seq_len": 1024,
   "train_step_ms": 2632.3,
   "peak_train_mb": 1999.7,
   "train_tokens_per_s": 3112,
   "decode_per_token_ms": 1.3894,
   "decode_mode": "stepwise (O(1) state)",
   "oom": false
  },
  {
   "model": "mamba",
   "seq_len": 2048,
   "train_step_ms": 10726.96,
   "peak_train_mb": 3970.9,
   "train_tokens_per_s": 1527,
   "decode_per_token_ms": 1.3458,
   "decode_mode": "stepwise (O(1) state)",
   "oom": false
  },
  {
   "model": "mamba",
   "seq_len": 4096,
   "train_step_ms": 248138.47,
   "peak_train_mb": 7912.6,
   "train_tokens_per_s": 132,
   "decode_per_token_ms": 1.9285,
   "decode_mode": "stepwise (O(1) state)",
   "oom": false
  },
  {
   "model": "mamba3",
   "seq_len": 1024,
   "train_step_ms": 10880.38,
   "peak_train_mb": 6646.7,
   "train_tokens_per_s": 753,
   "decode_per_token_ms": 1.2106,
   "decode_mode": "sequential scan over full sequence (per-token = time/T)",
   "oom": false
  },
  {
   "model": "mamba3",
   "seq_len": 2048,
   "train_step_ms": null,
   "peak_train_mb": null,
   "train_tokens_per_s": null,
   "decode_per_token_ms": null,
   "decode_mode": null,
   "oom": true
  },
  {
   "model": "mamba3",
   "seq_len": 4096,
   "train_step_ms": null,
   "peak_train_mb": null,
   "train_tokens_per_s": null,
   "decode_per_token_ms": null,
   "decode_mode": null,
   "oom": true
  }
 ]
};
